import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
// Generated by scripts/tailwind-jit.js (see package.json pre* scripts): newer
// Tailwind classes that Tailwind 1.9 cannot produce. Must load after index.css.
import './tailwind-jit.css';
import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

